# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiffableContacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LBTATools'	
  # Pods for DiffableContacts

  target 'DiffableContactsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiffableContactsUITests' do
    # Pods for testing
	
  end



end
